経費按分計算モジュール追加
WaitShimizu/EZTaxCraft pull request #4
Opened 2024-01-23 10:31 UTC by NatsukiShimizu

経費按分計算モジュール追加 #3

2024-01-23 10:38 UTC, WaitShimizu commented on eztaxcraft_app/subpackage/proration.py
> +        return int(required_expenses)
int型でキャストしているが、切り捨て？切り上げ？
ここでの四捨五入に関しての正当性を調査して正しい値が呼び出しもとに返せているのかを確認してください。

※23行目の [ cost * ratio ] を [ cost * int(ratio) ] のような形にすることでこの問題が解決できるかも検討してください。

2024-01-23 10:39 UTC, WaitShimizu commented on eztaxcraft_app/subpackage/proration.py
> +    def calc_expenses(self, source_value: float, target_value: float, cost: int) -> int:
1か月の経費を表す場合は変数名に_per_monthなどで意味を明確にすると呼び出す側は引数に必要な情報が連想しやすくなります。
可能なら引数名を修正してください。

2024-01-23 10:58 UTC, NatsukiShimizu commented on eztaxcraft_app/subpackage/proration.py
> +    def calc_expenses(self, source_value: float, target_value: float, cost: int) -> int:
該当箇所の引数名を修正しています。
修正対象のコミットID：Commit: 78408daac03670d031cc4b7f85d6fdaad60a332d

2024-01-23 11:27 UTC, NatsukiShimizu commented on eztaxcraft_app/subpackage/proration.py
> +        return int(required_expenses)
該当箇所を切り上げのint型で処理するように対応しています。
修正対象のコミットID：bd8a7a86d2506062ed6da4eb0cdd42531b2dec0a

2024-01-24 01:55 UTC, WaitShimizu requested changes
指摘内容を確認して適宜修正してください。
また「app_utiliry」ディレクトリにある「proration_calc.py」ファイルが不要になったのであれば削除をお願いします。

2024-01-24 01:55 UTC, WaitShimizu commented on eztaxcraft_app/subpackage/proration.py
> +    print(f'経費：{result_val:,.0f}円')
ここのif文は不要なため削除してください。

2024-01-24 08:57 UTC, NatsukiShimizu commented on eztaxcraft_app/subpackage/proration.py
> +    print(f'経費：{result_val:,.0f}円')
該当箇所のコードを削除しています。
かつ他処理でメソッド化できるものをメソッド化しています。
修正対象のコミットID：cd49ed787ba04d2e8f2a35da8f7af9ca8b5f2289

2024-01-24 08:58 UTC, NatsukiShimizu commented on eztaxcraft_app/subpackage/proration.py
> +    print(f'経費：{result_val:,.0f}円')
指摘にある「app_utiliry」ディレクトリにある「proration_calc.py」ファイルは削除しています。

2024-01-24 10:40 UTC, WaitShimizu requested changes
修正箇所を確認しました。
指摘箇所を確認して修正して下さい。

2024-01-24 10:40 UTC, WaitShimizu commented on eztaxcraft_app/subpackage/proration.py
> +    def calc_expenses(self, comparison_value: float, comparison_original_value: float, _per_month: int) -> int:
引数の「_per_month」だけアンダースコアが付与されていますが、他の引数には付与されていません。
何か明確に分ける理由がなければアンダースコア無しで統一してください。

2024-01-24 10:40 UTC, WaitShimizu commented on eztaxcraft_app/subpackage/proration.py
> +            print('')
ここでの変数のタイプチェックは不要かと思います。
削除をお願いします。

2024-01-24 10:40 UTC, WaitShimizu commented on eztaxcraft_app/subpackage/proration.py
> +        """按分詳細比率を取得する
内部処理用のメソッドに関しては以下のように「[内部処理用]」という記載を末尾に追加するように統一してください。

修正前：　"""按分詳細比率を取得する
修正後：　"""按分詳細比率を取得する [内部処理用]

2024-01-24 10:40 UTC, WaitShimizu commented on eztaxcraft_app/subpackage/proration.py
> +        """按分比率を取得する
他の箇所と同様の指摘になりますが、内部処理用のメソッドに関してはコメントも統一するようにしてください。

修正前：　"""按分比率を取得する
修正後：　"""按分比率を取得する [内部処理用]

2024-01-24 10:40 UTC, WaitShimizu commented on eztaxcraft_app/subpackage/proration.py
> +        result = int(round(round(proration_detail_rate,3)*100, 0))
該当箇所の処理の順番が逆のようです。
resultに値が設定される前にprint文で参照されています。

※ソースコードをコミットする前に動作を確認して実行時にエラーが発生しないかをしっかりと確認してください。本指摘箇所のままでは実行時にエラーが発生します。

2024-01-24 12:09 UTC, NatsukiShimizu commented on eztaxcraft_app/subpackage/proration.py
> +        result = int(round(round(proration_detail_rate,3)*100, 0))
該当箇所のコードの順番を修正しています。
また動作確認についてもpytestファイルを追加し動作確認をしています。
修正対象のコミットID：f3386a7144f6b5285a5131ba4c286a6154bcb0be

2024-01-24 12:20 UTC, NatsukiShimizu commented on eztaxcraft_app/subpackage/proration.py
> +    def calc_expenses(self, comparison_value: float, comparison_original_value: float, _per_month: int) -> int:
指摘箇所の変数名,コメントの文言を修正しました。
修正対象のコミットID：b46557128ab4ce2359ff7b33d1d3050b766b8d3f

2024-01-24 12:25 UTC, NatsukiShimizu commented on eztaxcraft_app/subpackage/proration.py
> +            print('')
指摘箇所の変数タイプチェックを削除しています。
修正対象のコミットID：dc39259df76554262b24dd88b3e3676e9352a25f

2024-01-24 12:29 UTC, NatsukiShimizu commented on eztaxcraft_app/subpackage/proration.py
> +        """按分詳細比率を取得する
指摘箇所の記載を修正しました。
修正対象のコミットID：0391c8faa17e3d3ad4abf5bb6c6df68daee4c1f5

2024-01-24 12:32 UTC, NatsukiShimizu commented on eztaxcraft_app/subpackage/proration.py
> +        """按分比率を取得する
指摘箇所のコメント文言を修正しました。
修正対象のコミットID：085003dab6b873ae4c4dd1871e3fa9b86beccfc0

2024-01-24 12:44 UTC, WaitShimizu approved these changes
修正内容を確認しました。
指摘はありません。

2024-01-24 12:46 UTC, merged